# use_frameworks!

platform :ios, '8.0'

target 'LWDynamicFont_Example' do
  pod 'LWDynamicFont', :path => '../'

  pod 'LWProgressView', :git => 'https://gitlab.com/ioslibraries1/libprogressview.git', :branch => 'master'

  # target 'LWDynamicFont_Tests' do
  #   inherit! :search_paths
  # end

end
