use_frameworks!

platform :ios, '8.0'

target 'libDynamicFont_Example' do
  pod 'libDynamicFont', :path => '../'

  pod 'libProgressView', :git => 'https://gitlab.com/luo-wei/libProgressView.git', :branch => 'master'

  # target 'libDynamicFont_Tests' do
  #   inherit! :search_paths
  # end

end
